RESPONSE_FIELD = "response"
SUCCESS_FIELD = "success"
MESSAGE_FIELD = "message"
USER_FIELD = "user"
EMAIL_FIELD = "email"
PASSWORD_FIELD = "password"
NAME_FIELD = "name"
ORDER_FIELD = "order"
NUMBER_FIELD = "number"
ORDERS_FIELD = "orders"
DATA_FIELD = "data"
INGREDIENTS_FIELD = "ingredients"
ACCESS_TOKEN_FIELD = "accessToken"

AUTHORIZATION_HEADER = "Authorization"

MESSAGE_USER_EXISTS = "User already exists"
MESSAGE_REQUIRED_FIELDS = "Email, password and name are required fields"
MESSAGE_INCORRECT_CREDENTIALS = "email or password are incorrect"
MESSAGE_NOT_AUTHORISED = "You should be authorised"
MESSAGE_INGREDIENTS_REQUIRED = "Ingredient ids must be provided"

ERROR_CREATE_USER_200 = "Ожидался код 200 при создании пользователя, получен {status_code}"
ERROR_CREATE_USER_403 = "Ожидался код 403, получен {status_code}"
ERROR_LOGIN_200 = "Ожидался код 200 при логине, получен {status_code}"
ERROR_LOGIN_401 = "Ожидался код 401, получен {status_code}"
ERROR_UPDATE_200 = "Ожидался код 200 при обновлении данных, получен {status_code}"
ERROR_UPDATE_401 = "Ожидался код 401 без авторизации, получен {status_code}"
ERROR_CREATE_ORDER_200 = "Ожидался код 200 при создании заказа, получен {status_code}"
ERROR_CREATE_ORDER_400 = "Ожидался код 400 без ингредиентов, получен {status_code}"
ERROR_CREATE_ORDER_400_INVALID = "Ожидался код 400 при невалидном хеше, получен {status_code}"
ERROR_GET_ORDERS_200 = "Ожидался код 200 при получении заказов, получен {status_code}"
ERROR_GET_ORDERS_401 = "Ожидался код 401 без авторизации, получен {status_code}"